-- ==========================================
-- COPIE des données de "3ème" vers "trévoux"
-- ==========================================

-- Sauvegarder d'abord les données actuelles de Trévoux (backup)
CREATE TABLE IF NOT EXISTS infos_gites_backup_trevoux AS 
SELECT * FROM infos_gites WHERE gite = 'trévoux';

-- Mettre à jour Trévoux avec les données de 3ème
UPDATE infos_gites AS target
SET 
    adresse = source.adresse,
    telephone = source.telephone,
    gps_lat = source.gps_lat,
    gps_lon = source.gps_lon,
    email = source.email,
    adresse_en = source.adresse_en,
    telephone_en = source.telephone_en,
    email_en = source.email_en,
    wifi_ssid = source.wifi_ssid,
    wifi_password = source.wifi_password,
    wifi_debit = source.wifi_debit,
    wifi_localisation = source.wifi_localisation,
    wifi_zones = source.wifi_zones,
    wifi_ssid_en = source.wifi_ssid_en,
    wifi_password_en = source.wifi_password_en,
    wifi_debit_en = source.wifi_debit_en,
    wifi_localisation_en = source.wifi_localisation_en,
    wifi_zones_en = source.wifi_zones_en,
    heure_arrivee = source.heure_arrivee,
    arrivee_tardive = source.arrivee_tardive,
    parking_dispo = source.parking_dispo,
    parking_places = source.parking_places,
    parking_details = source.parking_details,
    type_acces = source.type_acces,
    code_acces = source.code_acces,
    instructions_cles = source.instructions_cles,
    etage = source.etage,
    ascenseur = source.ascenseur,
    itineraire_logement = source.itineraire_logement,
    premiere_visite = source.premiere_visite,
    heure_arrivee_en = source.heure_arrivee_en,
    arrivee_tardive_en = source.arrivee_tardive_en,
    parking_dispo_en = source.parking_dispo_en,
    parking_places_en = source.parking_places_en,
    parking_details_en = source.parking_details_en,
    type_acces_en = source.type_acces_en,
    code_acces_en = source.code_acces_en,
    instructions_cles_en = source.instructions_cles_en,
    etage_en = source.etage_en,
    ascenseur_en = source.ascenseur_en,
    itineraire_logement_en = source.itineraire_logement_en,
    premiere_visite_en = source.premiere_visite_en,
    type_chauffage = source.type_chauffage,
    climatisation = source.climatisation,
    instructions_chauffage = source.instructions_chauffage,
    equipements_cuisine = source.equipements_cuisine,
    instructions_four = source.instructions_four,
    instructions_plaques = source.instructions_plaques,
    instructions_lave_vaisselle = source.instructions_lave_vaisselle,
    instructions_lave_linge = source.instructions_lave_linge,
    seche_linge = source.seche_linge,
    fer_repasser = source.fer_repasser,
    linge_fourni = source.linge_fourni,
    configuration_chambres = source.configuration_chambres,
    type_chauffage_en = source.type_chauffage_en,
    climatisation_en = source.climatisation_en,
    instructions_chauffage_en = source.instructions_chauffage_en,
    equipements_cuisine_en = source.equipements_cuisine_en,
    instructions_four_en = source.instructions_four_en,
    instructions_plaques_en = source.instructions_plaques_en,
    instructions_lave_vaisselle_en = source.instructions_lave_vaisselle_en,
    instructions_lave_linge_en = source.instructions_lave_linge_en,
    seche_linge_en = source.seche_linge_en,
    fer_repasser_en = source.fer_repasser_en,
    linge_fourni_en = source.linge_fourni_en,
    configuration_chambres_en = source.configuration_chambres_en,
    instructions_tri = source.instructions_tri,
    jours_collecte = source.jours_collecte,
    decheterie = source.decheterie,
    instructions_tri_en = source.instructions_tri_en,
    jours_collecte_en = source.jours_collecte_en,
    decheterie_en = source.decheterie_en,
    detecteur_fumee = source.detecteur_fumee,
    extincteur = source.extincteur,
    coupure_eau = source.coupure_eau,
    disjoncteur = source.disjoncteur,
    consignes_urgence = source.consignes_urgence,
    detecteur_fumee_en = source.detecteur_fumee_en,
    extincteur_en = source.extincteur_en,
    coupure_eau_en = source.coupure_eau_en,
    disjoncteur_en = source.disjoncteur_en,
    consignes_urgence_en = source.consignes_urgence_en,
    heure_depart = source.heure_depart,
    depart_tardif = source.depart_tardif,
    checklist_depart = source.checklist_depart,
    restitution_cles = source.restitution_cles,
    heure_depart_en = source.heure_depart_en,
    depart_tardif_en = source.depart_tardif_en,
    checklist_depart_en = source.checklist_depart_en,
    restitution_cles_en = source.restitution_cles_en,
    tabac = source.tabac,
    animaux = source.animaux,
    nb_max_personnes = source.nb_max_personnes,
    caution = source.caution,
    tabac_en = source.tabac_en,
    animaux_en = source.animaux_en,
    nb_max_personnes_en = source.nb_max_personnes_en,
    caution_en = source.caution_en,
    date_modification = NOW()
FROM infos_gites AS source
WHERE source.gite = '3ème' 
AND target.gite = 'trévoux';

-- Vider les données du gîte "3ème" maintenant qu'elles sont copiées
UPDATE infos_gites
SET 
    adresse = NULL,
    telephone = NULL,
    gps_lat = NULL,
    gps_lon = NULL,
    email = NULL,
    adresse_en = NULL,
    telephone_en = NULL,
    email_en = NULL,
    wifi_ssid = NULL,
    wifi_password = NULL,
    wifi_debit = NULL,
    wifi_localisation = NULL,
    wifi_zones = NULL,
    wifi_ssid_en = NULL,
    wifi_password_en = NULL,
    wifi_debit_en = NULL,
    wifi_localisation_en = NULL,
    wifi_zones_en = NULL,
    date_modification = NOW()
WHERE gite = '3ème';

-- Vérifier les données copiées
SELECT 
    'Données copiées de 3ème vers trévoux' AS message,
    adresse,
    telephone,
    email,
    gps_lat,
    gps_lon
FROM infos_gites 
WHERE gite = 'trévoux';
